# Generated by Django 5.1.2 on 2024-10-19 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogpost_updated_at_blogpost_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='created_at',
            new_name='created_date',
        ),
    ]
